### ISSUE TITLE
Paperclipped is looking for dragdrop.js in the wrong place

### ISSUE THREAD

**Issue by jondkinney** [kbingman/paperclipped#12]
Not sure how it's being loaded, but paperclipped wants it at /javascripts/dragdrop.js but it is now in /javascripts/admin/dragdrop.js. For now I copied the one from the admin directory to the root of javascripts so that paperclipped will work, but I don't want to load the file twice forever.

Like I said, I'm not sure how or why paperclipped is looking where it is looking or I'd fix it and send a pull request.

Thanks,
-Jon

**Comment by kbingman** [comment]
This is a 0.9 issue. It was moved. Paperclipped does not support 0.9 yet.

**Comment by jondkinney** [comment]
Yea, sorry... I know it's a 0.9 issue. I have paperclipped working on 0.8.1 without issue. I was just throwing this out there for reference when you do to go update it.

Thanks,
-on

**Comment by kbingman** [comment]
John completely changed the javascripts in 0.9.0 and moved all the core scripts. Dragdrop is not actually loaded by radiant, which is why paperclipped needs to load it. I have a version running on 0.9.0, but I just started it yesterday. I will have a branch online shortly.

**Comment by jondkinney** [comment]
Awesome, thanks! I'll look for that sometime soon then.
