### ISSUE TITLE
problem with paperclipped (0.9 branch) + globalize2

### ISSUE THREAD

**Issue by txus** [kbingman/paperclipped#17]
Hi!

It seems that whenever paperclipped (0.9 branch) is loaded, any before_filter injected to ApplicationControllerExtensions by globalize2 won't work (specifically set_locale, which is essential to any locale stuff including changing languages).

After looking through paperclipped code at 0.9 branch, apparently there's no specific reference to neither locales nor other extensions... Any ideas?

Thank you :)

**Comment by kbingman** [comment]
Does it work without paperclipped. As far as I am aware, this is actually a Rails issue, but if it works without paperclipped, please let me know. I know that rails has had issues with before filters in the application_controller.

Keith

**Comment by oriolgual** [comment]
Yes, it works ok without it. Let us know if we can help you.

Cheers,
Oriol.
