### ISSUE TITLE
template_name method undefined

### ISSUE THREAD

**Issue by halan** [kbingman/paperclipped#2]
I have this problem since e20a79d0 in this file http://github.com/kbingman/paperclipped/tree/e20a79d0ccbd289b7e3fc38695952215ad29c469/app/views/assets/index.html.haml

I return to before it, and just work. The problem is with the regions.

**Comment by kbingman** [comment]
This is a known problem. at the moment it does not work with edge, but I am in the process of refactoring the regions. it should work with edge soon.

**Comment by kbingman** [comment]
The 0.8.0 version should work with the current 0.8.0 RC1 gem. Let me know if it doesn't
