### ISSUE TITLE
Thumbnail not being created

### ISSUE THREAD

**Issue by syntruth** [kbingman/paperclipped#22]
On uploaded images, the thumbnails are not being created, although the image asset is uploaded find and can be used as intended.  Not seeing any errors in the logs, made sure that public/assets is chown/chmod'd to allow www-data to write data, so not sure what I am missing.

**Comment by kbingman** [comment]
Check to see if ImageMagick is correctly installed (and all of its libraries), it silently fails if not.

**Comment by syntruth** [comment]
That was it, but not sure -what- I was missing, actually.  Did an update of IM and now it works. Thanks! :)

**Comment by kbingman** [comment]
Glad ro help. ImageMagick can be a real pain, there are just too many libraries
