### ISSUE TITLE
SQLException: no such table

### ISSUE THREAD

**Issue by Contexter** [kbingman/paperclipped#3]
Hi Keith!

When I try migrating -  it used to work but now - I get the following:

<pre><code>
rake production db:migrate:extensions --trace
(in /deploy/radiant)
** Invoke production (first_time)
** Execute production
** Invoke environment (first_time)
** Execute environment
** Invoke db:migrate:extensions (first_time)
** Invoke environment
** Execute db:migrate:extensions
rake aborted!
SQLite3::SQLException: no such table: extension_meta: SELECT schema_version FROM extension_meta WHERE name = 'Paperclipped'
/opt/ree/lib/ruby/gems/1.8/gems/radiant-0.7.1/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:147:in `log'
/opt/ree/lib/ruby/gems/1.8/gems/radiant-0.7.1/vendor/rails/activerecord/lib/active_record/connection_adapters/sqlite_adapter.rb:132:in `execute'
/opt/ree/lib/ruby/gems/1.8/gems/radiant-0.7.1/vendor/rails/activerecord/lib/active_record/connection_adapters/sqlite_adapter.rb:372:in `catch_schema_changes'
/opt/ree/lib/ruby/gems/1.8/gems/radiant-0.7.1/vendor/rails/activerecord/lib/active_record/connection_adapters/sqlite_adapter.rb:132:in `execute'
/opt/ree/lib/ruby/gems/1.8/gems/radiant-0.7.1/vendor/rails/activerecord/lib/active_record/connection_adapters/sqlite_adapter.rb:275:in `select'
/opt/ree/lib/ruby/gems/1.8/gems/radiant-0.7.1/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:7:in `select_all_without_query_cache'
/opt/ree/lib/ruby/gems/1.8/gems/radiant-0.7.1/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:61:in `select_all'
/opt/ree/lib/ruby/gems/1.8/gems/radiant-0.7.1/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:13:in `select_one'
/opt/ree/lib/ruby/gems/1.8/gems/radiant-0.7.1/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:19:in `select_value'
/opt/ree/lib/ruby/gems/1.8/gems/radiant-0.7.1/lib/radiant/extension_migrator.rb:42:in `initialize_extension_schema_migrations'
/opt/ree/lib/ruby/gems/1.8/gems/radiant-0.7.1/lib/radiant/extension_migrator.rb:25:in `initialize'
/opt/ree/lib/ruby/gems/1.8/gems/radiant-0.7.1/vendor/rails/activerecord/lib/active_record/migration.rb:373:in `new'
/opt/ree/lib/ruby/gems/1.8/gems/radiant-0.7.1/vendor/rails/activerecord/lib/active_record/migration.rb:373:in `up'
/opt/ree/lib/ruby/gems/1.8/gems/radiant-0.7.1/vendor/rails/activerecord/lib/active_record/migration.rb:356:in `migrate'
/opt/ree/lib/ruby/gems/1.8/gems/radiant-0.7.1/lib/radiant/extension_migrator.rb:7:in `migrate'
/opt/ree/lib/ruby/gems/1.8/gems/radiant-0.7.1/lib/radiant/extension_migrator.rb:12:in `migrate_extensions'
/opt/ree/lib/ruby/gems/1.8/gems/radiant-0.7.1/lib/radiant/extension_migrator.rb:11:in `each'
/opt/ree/lib/ruby/gems/1.8/gems/radiant-0.7.1/lib/radiant/extension_migrator.rb:11:in `migrate_extensions'
/opt/ree/lib/ruby/gems/1.8/gems/radiant-0.7.1/lib/tasks/extensions.rake:8
/opt/ree/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:617:in `call'
/opt/ree/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:617:in `execute'
/opt/ree/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:612:in `each'
/opt/ree/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:612:in `execute'
/opt/ree/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:578:in `invoke_with_call_chain'
/opt/ree/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/opt/ree/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:571:in `invoke_with_call_chain'
/opt/ree/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:564:in `invoke'
/opt/ree/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:2027:in `invoke_task'
/opt/ree/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:2005:in `top_level'
/opt/ree/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:2005:in `each'
/opt/ree/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:2005:in `top_level'
/opt/ree/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:2044:in `standard_exception_handling'
/opt/ree/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:1999:in `top_level'
/opt/ree/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:1977:in `run'
/opt/ree/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:2044:in `standard_exception_handling'
/opt/ree/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:1974:in `run'
/opt/ree/lib/ruby/gems/1.8/gems/rake-0.8.4/bin/rake:31
/opt/ree/bin/rake:19:in `load'
/opt/ree/bin/rake:19
</code></pre>

Any idea?

Greetings from Berlin by
Benedikt

**Comment by kbingman** [comment]
Hmm. weird. That is the old table from pre 0.7 radiant. which version of radiant are you using?

**Comment by Contexter** [comment]
Hi Keith,

Radiant 0.7.1 - the biggest problem is that extension migration is impossible now ... any idea?

Thanx and greetings from Berlin

Bene
