### ISSUE TITLE
0.8.0 Branch - edit page conflicts experienced with multiple extensions present

### ISSUE THREAD

**Issue by bellroy** [kbingman/paperclipped#5]
We have an extension that gets run before the paperclipped extension which does the following during activation:

```
admin.page.edit.add :form_bottom, "/preview/show", :after => 'edit_buttons'
admin.page.edit.add :form_bottom, "/preview/preview_iframe", :after => 'edit_buttons'
```

It appears that when the paperclipped extension is activated that it changes the edit page in paperclipped/lib/assets_admin_ui.rb line 32 which does:

```
        page.edit = Radiant::AdminUI::RegionSet.new do |edit|
          edit.main.concat %w{edit_header edit_form edit_popups }
          edit.form.concat %w{edit_title edit_extended_metadata edit_page_parts}
          edit.form_bottom.concat %w{edit_buttons}
          edit.parts_bottom.concat %w{edit_layout_and_type edit_timestamp}
          edit.asset_tabs.concat %w{attachment_tab upload_tab bucket_tab search_tab}
          edit.bucket_pane.concat %w{bucket_notes bucket bucket_bottom}
          edit.asset_panes.concat %w{page_attachments upload search}
```

If the assignment to page.edit is commented out then we can observe that the preview button added by the first extension is present and works.  Is it possible that the paperclipped extension is somehow overwriting the existing page.edit?  Is there a way to do this without interfering with other extension (if indeed that is what's happening here?)

**Comment by kbingman** [comment]
Can you let know which extension that is. The preview (with an iFrame) extension? I have used that successfully with 0.7.1 but have not tried it out with the newer version (which btw is _not_ ready for primetime...!)

Keith

**Comment by jgoggles** [comment]
I'm having the same problem with Paperclipped 0.7.1 - it seems it's conflicting with the featured_pages extension which does this during activation:

admin.page.edit.add :form, "featured_page_meta"

**Comment by kbingman** [comment]
this should now be fixed
